#!/bin/bash
set -eux

# this is a simple config for herbstluftwm

herbstclient unrule -F
#function herbstclient() {
#    /home/bkero/code/herbstluftwm/herbstclient "$@"
#}

herbstclient emit_hook reload

xsetroot -solid '#5A8E3A'


# remove all existing keybindings
herbstclient keyunbind --all

# keybindings
Mod=Mod4
#Mod=Mod1
herbstclient keybind $Mod-Shift-q quit
herbstclient keybind $Mod-Shift-r reload
herbstclient keybind $Mod-Shift-c close
#herbstclient keybind $Mod-Return spawn urxvt256c-ml
#herbstclient keybind $Mod-Return spawn kitty
herbstclient keybind $Mod-Return spawn alacritty
herbstclient keybind $Mod-Shift-Return spawn kitty
herbstclient keybind $Mod-Shift-grave spawn urxvt

#herbstclient keybind XF86MonBrightnessDown spawn brightnessctl -d intel_backlight set 8%-
#herbstclient keybind XF86MonBrightnessUp spawn brightnessctl -d intel_backlight set 8%+
herbstclient keybind XF86MonBrightnessDown spawn /home/bkero/.bin/brightness-down.sh
herbstclient keybind XF86MonBrightnessUp spawn /home/bkero/.bin/brightness-up.sh
herbstclient keybind XF86AudioRaiseVolume spawn /home/bkero/.bin/volume-up.sh
herbstclient keybind XF86AudioLowerVolume spawn /home/bkero/.bin/volume-down.sh
herbstclient keybind XF86AudioMute spawn /home/bkero/.bin/mute.sh
#herbstclient keybind XF86AudioRaiseVolume spawn amixer set Master 7%+
#herbstclient keybind XF86AudioLowerVolume spawn amixer set Master 7%-
#herbstclient keybind XF86AudioMute spawn amixer set Master toggle

# Set transparent background for wallpapers
herbstclient set frame_bg_transparent '1'

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

herbstclient rename default "${TAG_NAMES[0]}" || true
for i in "${!TAG_NAMES[@]}" ; do
    herbstclient add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        herbstclient keybind "$Mod-$key" use_index "$i"
        herbstclient keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
herbstclient keybind $Mod-period use_index +1
herbstclient keybind $Mod-comma  use_index -1
herbstclient keybind $Mod-Right  use_index +1
herbstclient keybind $Mod-Left   use_index -1
herbstclient keybind XF86Back    use_index -1
herbstclient keybind XF86Forward use_index +1

# layouting
herbstclient keybind $Mod-r remove
herbstclient keybind $Mod-space cycle_layout 1
herbstclient keybind $Mod-v split vertical 0.5
herbstclient keybind $Mod-Shift-v split horizontal 0.5
herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
herbstclient keybind $Mod-Control-h resize left +$RESIZESTEP
herbstclient keybind $Mod-Control-j resize down +$RESIZESTEP
herbstclient keybind $Mod-Control-k resize up +$RESIZESTEP
herbstclient keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
herbstclient mouseunbind --all
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 resize
herbstclient mousebind $Mod-Button3 zoom

# focus
herbstclient keybind $Mod-BackSpace   cycle_monitor
herbstclient keybind $Mod-Tab         cycle_all +1
herbstclient keybind $Mod-Shift-Tab   cycle_all -1
herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-h focus left
herbstclient keybind $Mod-j focus down
herbstclient keybind $Mod-k focus up
herbstclient keybind $Mod-l focus right
herbstclient keybind $Mod-Shift-h shift left
herbstclient keybind $Mod-Shift-j shift down
herbstclient keybind $Mod-Shift-k shift up
herbstclient keybind $Mod-Shift-l shift right


# colors
herbstclient set frame_border_active_color '#222222'
herbstclient set frame_border_normal_color '#101010'
herbstclient set frame_bg_normal_color '#565656'
herbstclient set frame_bg_active_color '#345F0C'
herbstclient set frame_border_width 0
herbstclient set window_border_width 2
herbstclient set window_border_normal_color '#454545'
herbstclient set window_border_active_color '#9fbc00'
herbstclient set always_show_frame 1
herbstclient set window_gap 0
herbstclient set frame_gap 0

# rules
herbstclient unrule -F
#herbstclient rule class=XTerm tag=3 # move all xterms to tag 3
herbstclient rule focus=on # normally do not focus new clients
# give focus to most common terminals
herbstclient rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
herbstclient unlock

# do multi monitor setup here, e.g.:
# herbstclient remove_monitor 1
# herbstclient move_monitor 0 1280x1024+0+0
# herbstclient add_monitor 1280x1024+1280+0

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    $panel $monitor &
#done

herbstclient pad 0 28 0 0
herbstclient rule class~"Conky" manage=off
herbstclient rule title~"^conky" manage=off
herbstclient rule title="stalonetray" manage=off
herbstclient rule title="safeeyes" focus=on fullscreen=on

[ -p "$HOME/.xobpipe" ] || mkfifo "$HOME/.xobpipe"
tail -f "$HOME/.xobpipe" | "$HOME/code/xob/xob" > /dev/null &
conky &
sleep 2
stalonetray &
nm-applet &
safeeyes &
pasystray &
#(source $HOME/.venv3/bin/activate; safeeyes) &
ibus-daemon -dxr
redshift-gtk -l 45.54117:-122.6581785 & # Portland
#redshift-gtk -l 37.800293:12.430397 & # Sambuca di Sicilia
#redshift-gtk -l 12.152180:119.917401 & # Busuanga
dunst &
nextcloud &
#compton --vsync drm --backend xr_glx_hybrid --vsync-use-glfinish --glx-no-stencil &
/home/bkero/code/weelisten/client.py irc.bke.ro Me7chee6PaaFe4oh -p 7000 &
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
eval $(op signin my)
